categories: [Text Manipulation]
description: Wrapper for the program which renames the scaffold
homepage_url: 'https://github.com/Yating-L/rename_scaffold'
long_description: This tool is to rename scaffolds in reference genome so that the sequence names are less than 31 characters. Rename all scaffolds to scaffold_1, scaffold_2, ..., scaffold_N and provide a name mapping file
name: rename_scaffolds
owner: yating-l
